
  
spring:
  datasource:
    username: root
    password: baba
    url: jdbc:mysql://localhost:3306/projectdb
    
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
     
    
destination: C:\\Users\\BabaFakruddinDharuba\\Desktop\\Project\\Templates\\flattenPdf\\
